### PR TITLE
Item pg: Pass some props into main content

### PR DESCRIPTION
**Pull request by amardesi**
Also rearranged components in JSX a bit

### CODE REVIEW

**Comment by amardesi** [comment]
@martinhaye  Now setting state.currentTab at highest component so it can be changed from right column area. But for some reason the Content for tab 1 is not loading upon first render.

**Comment by martinhaye** [comment]
If you want it to be part of the initial state, then I think currentTab needs to be set as part of that initial state by escholApp. I'll give it a try to make sure.

**Comment by martinhaye** [comment]
Yep. Add ":currentTab => 1" to your genAppPage call.

**Comment by amardesi** [comment]
But I'm setting it here on first render:
ReactDOM.render(<ItemPage currentTab="1" ...

**Comment by amardesi** [comment]
I suppose we may end up wanting to instantiate it via genAppPage. Keeping it in the JSX (may I propose we keep it in the JSK for now?) value has to be quoted, which turns it into a string. Fixed for now by casting it as a Number in the constructor.

**Comment by martinhaye** [comment]
The fix is plenty good for now. As we incrementally understand more about application state (and we will; Joel and Amy are working on it too), we'll rework. Probably several times as we learn more and more :)

**Pull request merged**
